### ISSUE TITLE
Update language bindings to avoid py-tree-sitter "removed in v0.22.0" (next version!) warning

### ISSUE THREAD

**Issue by vintagedave** [Isopod/tree-sitter-pascal#3]
Hello,

First - I love that you are providing a treesitter grammar for Pascal and Delphi. Thankyou.

Using it from Python, I found I needed to use the [build from source](https://github.com/tree-sitter/py-tree-sitter/blob/master/README.md#build-from-source) setup, ie cloning and then using `Language.build_library` to use my system's inbuilt C compiler to build the dynamic library.

The `py-tree-sitter` project [warns](https://github.com/tree-sitter/py-tree-sitter/blob/master/README.md#build-from-source) that treesitter libraries need to update their bindings, and that this method won't be available in 0.22 -- which is the next version!

Would it be possible to update the bindings to suit the upcoming API change please?

(It's possible you don't support Python -- this is a treesitter grammar repo, not a Python repo :)  I can have a go myself if so. I have zero idea what's involved in updating to match the new requirement. Figured it's worth filing an issue and asking here first!)

**Comment by Isopod** [comment]
Hi,

thanks for informing me of this. I did not know I also had to ship the stuff in `bindings/`. Can you try this #4 branch? Does that fix it?

**Comment by vintagedave** [comment]
Thankyou! I am not quite sure how to best test it. Usually this would be a Python package, but working around it by putting it in a folder, I have code like:

```python
import treesitterpascal.bindings.python.tree_sitter_pascal as pascal
from tree_sitter import Language, Parser

PASCAL_LANGUAGE = Language(pascal.language(), "pascal")
```
and that gives,
`ModuleNotFoundError: No module named 'treesitterpascal.bindings.python.tree_sitter_pascal._binding'`

I see the __init__.py file is referring to ".binding", but I don't see where that's defined. Nor, I'm afraid, do I know enough about Python packages to quite understand the structure. I do see __init__.pyi (with a I in the extension) has a language defined.

When I look at the Python treesitter bindings for Python, I see an extra folder: https://github.com/tree-sitter/tree-sitter-python/blob/master/bindings/python/build/lib/tree_sitter_python/__init__.py

**Comment by Isopod** [comment]
Unfortunately I don't know much about Python, either. I found a [comment](https://github.com/tree-sitter/tree-sitter-python/issues/262#issuecomment-2077638647) that says you can install a package with pip from a URL. I don't know if it's possible to specify a branch, but perhaps it also works with a local path?

I don't see any `bindings/python/build` directory in my local folder. Even after re-running `tree-sitter generate` and `tree-sitter build` it is not being generated.

**Comment by ObserverOfTime** [comment]
> I don't know if it's possible to specify a branch, but perhaps it also works with a local path?

```bash
pip install git+https://github.com/Isopod/tree-sitter-pascal@language-bindings
```

> I don't see any `bindings/python/build` directory in my local folder.

That directory should not be there.

**Comment by vintagedave** [comment]
I have not succeeded in getting this to work yet, but as noted I'm not an expert here. Mostly commenting just to let you know I have not forgotten the issue, and have continued to spend a some time here and there testing it.

**Comment by vintagedave** [comment]
@Isopod Would it be possible to email you about something related to this repo, please? I can't find contact details for you on the repo. If you email me, my email address is my username at gmail.com.

Thankyou!

(Please write here when you've emailed because I get a hundred or more emails a day to that address and either miss some or spam filters get some :()
