### ISSUE TITLE
{$IFDEF} and {$IFNDEF} inside a type declaration causes incorrect node holding the rest of the text and macros

### ISSUE THREAD

**Issue by vintagedave** [Isopod/tree-sitter-pascal#7]
Hello,

Testing against the following Delphi code:
```Delphi
        unit Ifdefs;
        interface
        type
            {$IF DEFINED(MSWINDOWS)}IWindowsOnly = interface end;{$ELSE}ISomethingElse = interface end;{$ENDIF}
            {$IFDEF NOTDEFINED}
                INotDefined
            {$ELSE}
                IInverse
            {$ENDIF} = interface end;
```
I get some odd node results for the IFDEF part.

* The $IFDEF comes in as a node type "pp", as expected
* The following node is a declType, as expected
* But the node's first child is type "genericDot", representing the whole "b'INotDefined\n            {$ELSE}\n                IInverse'" section.

In other words, it doesn't seem to recognise the type name, and the $ELSE is lost. (I originally found this with $IFNDEF, so it seems to apply to both.)

On the other hand, the preceding declaration beginning $IF DEFINED does seem to generate the expected nodes. It may be that this is because they are entire typename = definition clauses, whereas the failing ones have IFDEF logic inserted in the middle?

**Comment by vintagedave** [comment]
By the way, one of the ancestor nodes here is also of type ERROR. I see this quite a bit parsing complex units (eg Winapi.Windows.pas.) It doesn't seem to affect things badly; I ignore ERROR nodes when using the nodes.

**Comment by vintagedave** [comment]
Gotcha. I think this is a rare enough case (ifdef with this specific pattern, two definitions of the same type) it's not worth trying to fix -- I saw the comment about doing so sparingly.

I've been using this from Python btw, and also evaluating ifdefs to build a map of 'real' code vs ifdef-ed out code. I hope to blog about it sometime. But it is actually using it to get the nodes that _should_ be looked at.

Do you think (would you recommend) some way to do this before, or inside, treesitter? I don't want to modify the code by actually removing ifdef-ed out portions, but I wonder if there's a way to cause the parsing to ignore specific ranges?

**Comment by Isopod** [comment]
By the way, I just came across this: https://docs.rs/tree-sitter/latest/tree_sitter/struct.Parser.html#method.set_included_ranges

This might be what you are looking for. While the reference is for the Rust binding, I assume that the same function is available in other language bindings.

**Comment by respectify-dave** [comment]
That's very interesting, thankyou for sharing!

**Comment by vintagedave** [comment]
That's very interesting - thankyou for sharing!
