### ISSUE TITLE
Lack of `break` and `continue` nodes

### ISSUE THREAD

**Issue by natalia-nikoladze** [Isopod/tree-sitter-pascal#9]
Hello,

While testing the following Pascal program: 
```pascal
program Loop;
var
    i : integer;
begin
    i := 0;
    while true do
    begin
        if i >= 10 then
            break;
        i += 1;
    end;
end.
```

I was surprised to find that the `break` statement was treated as an identifier. This is the tree that was created:
```
root
    program
        kProgram
        moduleName
            identifier
        ;
        declVars
            kVar
            declVar
                identifier
                :
                type
                    typeref
                        identifier
                ;
        block
            kBegin
            assignment
                identifier
                kAssign
                literalNumber
            ;
            while
                kWhile
                kTrue
                kDo
                block
                    kBegin
                    if
                        kIf
                        exprBinary
                            identifier
                            kGte
                            literalNumber
                        kThen
                        statement
                            identifier
                            ;
                    assignment
                        identifier
                        kAssignAdd
                        literalNumber
                    ;
                    kEnd
                    ;
            kEnd
        kEndDot
            .
```
After checking the grammar, I noticed that the `break` and `continue` keywords are not handled at all. However, according to [these](https://www.freepascal.org/docs-html/rtl/system/break.html) [sources](https://www.freepascal.org/docs-html/rtl/system/continue.html), they can both be used in pascal.
Is there a reason why they are not included in the grammar?

Thanks!

**Comment by Isopod** [comment]
They are technically identifiers and not keywords as you can declare a variable called `break`. Try it yourself. It's a weird fact about Pascal. There is even a name for these special kinds of identifiers that I forgot. It even says it on the documentation page you linked:
>Note that although Break is a compiler intrinsic (i.e. is treated specially) it is defined as a procedure in the system unit, and hence can be redefined.

This isn't just true of Freepascal by the way, it's true of Pascal in general. `Continue`, `break`, `exit` etc. are *not* keywords, unlike in most other programming languages. I have no idea why it is this way. Must have historic reasons.
